#!/usr/bin/env Rscript
# MICB 475 project 2: making publication ready graphs, running permanova stats that are controlled for birth mode 
# Emily 2023-11-14/15

library(phyloseq)
library(ape)
library(tidyverse)
library(vegan)  
library(picante)
library(ggplot2)
library(dplyr)

# load in R data 
load("all_BMI_phyloseq_rare_new.RData")

#### Bray-Curtis Evaluation #### 
# Evaluate Bray-Curtis for mom BMI 
bc_distance_BMI <- distance(all_BMI_phyloseq_rare_new, method="bray")
pcoa_bc_BMI <- ordinate(all_BMI_phyloseq_rare_new, method="PCoA", distance=bc_distance_BMI)

# Create plot  
pcoa_bray_BMI_categorical_unedited <- plot_ordination(all_BMI_phyloseq_rare_new, pcoa_bc_BMI, color = "mom_bmi_label") +
  labs(col = "Mom BMI")
# view plot 
print(pcoa_bray_BMI_categorical_unedited)

# Make plot publication ready 
pcoa_bray_BMI_categorical_pub_ready <- plot_ordination(all_BMI_phyloseq_rare_new, pcoa_bc_BMI, 
                                                    color = "mom_bmi_label", shape = "mom_bmi_label") +
  scale_color_manual(values = c("red", "blue")) + # change colors
  scale_shape_manual(values = c(1,1)) + # change shape
  labs(col = "Mom BMI") + # change label
  ggtitle("Bray Curtis for Mom BMI") +  # add title
  theme(
    plot.title = element_text(hjust = 0.5),  # centre title
    panel.background = element_rect(fill = "white"),  # Set background color to white
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line = element_blank(), # Remove axis lines
    panel.border = element_rect(color = "black", fill = NA, size = 0.5), # add border 
    legend.key = element_rect(fill = "white")) + # Set legend background color to white 
  geom_hline(yintercept = 0, linetype = "dashed",color = "black", size = 0.25) + # add intercept at 0.0 
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", size = 0.25) + # add intercept at 0.0 
  stat_ellipse(aes(fill = mom_bmi_label), level = 0.95, alpha = 0.3) +# Add ellipses 
  guides(shape = FALSE) # remove legend for shape 

print(pcoa_bray_BMI_categorical_pub_ready)

# Save plot
ggsave("PCoA Bray Curtis for BMI Publication ready.png", 
       plot = pcoa_bray_BMI_categorical_pub_ready, 
       height = 4, width = 5)

# Evaluate Bray Curtis for feed_mode 
bc_distance_feed_mode <- distance(all_BMI_phyloseq_rare_new, method="bray")
pcoa_bc_feed_mode <- ordinate(all_BMI_phyloseq_rare_new, method="PCoA", distance=bc_distance_feed_mode)

# Create plot 
pcoa_bc_feed_mode_plot <- plot_ordination(all_BMI_phyloseq_rare_new, pcoa_bc_feed_mode, color = "feed") +
  labs(col = "feed")
print(pcoa_bc_feed_mode_plot)

# Make plot publication ready 
pcoa_bc_feed_mode_pub_ready <- plot_ordination(all_BMI_phyloseq_rare_new, pcoa_bc_feed_mode, 
                                               color = "feed", shape = "feed") +
  scale_color_manual(values = c("red", "blue")) + #change colors
  scale_shape_manual(values = c(1,1)) + # change shapes
  labs(col = "Feed Mode") + # change label
  ggtitle("Bray Curtis for Feed Mode") +  # add title
  theme(
    plot.title = element_text(hjust = 0.5),  # centre title
    panel.background = element_rect(fill = "white"),  # Set background color to white
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line = element_blank(), # remove axis lines 
    panel.border = element_rect(color = "black", fill = NA, size = 0.5), # add border 
    legend.key = element_rect(fill = "white")) + # Set legend background color to white 
  geom_hline(yintercept = 0, linetype = "dashed",color = "black", size = 0.25) + # add intercept at 0.0 
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", size = 0.25) + # add intercept at 0.0 
  stat_ellipse(aes(fill = feed), level = 0.95, alpha = 0.3) + # Add ellipses 
  guides(shape = FALSE) # remove legend for shape 

print(pcoa_bc_feed_mode_pub_ready)

# Save plot
ggsave("PCoA Bray Curtis for Feed Mode Publication Ready.png", 
       plot = pcoa_bc_feed_mode_pub_ready, 
       height = 4, width = 5)

#### Weighted UniFrac #### 
# Evaluate Weighted UniFrac for mom BMI 
wu_distance_BMI <- distance(all_BMI_phyloseq_rare_new, method="unifrac", weighted=TRUE)
pcoa_wu_BMI <- ordinate(all_BMI_phyloseq_rare_new, method="PCoA", distance=wu_distance_BMI)

plot_ordination(all_BMI_phyloseq_rare_new, pcoa_wu_BMI, color = "mom_bmi_label")

# Create plot 
pcoa_wu_BMI_categorical <- plot_ordination(all_BMI_phyloseq_rare_new, pcoa_wu_BMI, color = "mom_bmi_label") +
  labs(col = "Mom BMI")
print(pcoa_wu_BMI_categorical)

# Make plot publication ready 
pcoa_wu_BMI_categorical_pub_ready <- plot_ordination(all_BMI_phyloseq_rare_new, pcoa_wu_BMI, 
                                                       color = "mom_bmi_label", shape = "mom_bmi_label") +
  scale_color_manual(values = c("red", "blue")) + 
  scale_shape_manual(values = c(1,1)) +
  labs(col = "Mom BMI") + 
  ggtitle("Weighted Unifrac for Mom BMI") +  # add title
  theme(
    plot.title = element_text(hjust = 0.5),  # centre title
    panel.background = element_rect(fill = "white"),  # Set background color to white
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line = element_blank(), # Remove axis lines
    panel.border = element_rect(color = "black", fill = NA, size = 0.5), # add border 
    legend.key = element_rect(fill = "white")) + # Set legend background color to white 
  geom_hline(yintercept = 0, linetype = "dashed",color = "black", size = 0.25) + # add intercept at 0.0 
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", size = 0.25) + # add intercept at 0.0 
  stat_ellipse(aes(fill = mom_bmi_label), level = 0.95, alpha = 0.3) +# Add ellipses 
  guides(shape = FALSE) # remove legend for shape 

print(pcoa_wu_BMI_categorical_pub_ready)

# Save plot
ggsave("PCoA Weighted Unifrac for BMI Publication Ready.png", 
       plot = pcoa_wu_BMI_categorical_pub_ready, 
       height = 4, width = 5)

# Evaluate Weighted UniFrac for feeding mode 
wu_distance_feed_mode <- distance(all_BMI_phyloseq_rare_new, method="unifrac", weighted=TRUE)
pcoa_wu_feed_mode <- ordinate(all_BMI_phyloseq_rare_new, method="PCoA", distance=wu_distance_feed_mode)

# Create plot 
pcoa_wu_feed_mode_plot <- plot_ordination(all_BMI_phyloseq_rare_new, pcoa_wu_feed_mode, color = "feed") +
  labs(col = "feed")
print(pcoa_wu_feed_mode_plot)

# Make plot publication ready 
pcoa_wu_feed_mode_pub_ready <- plot_ordination(all_BMI_phyloseq_rare_new, pcoa_wu_feed_mode, 
                                               color = "feed", shape = "feed") +
  scale_color_manual(values = c("red", "blue")) + # change colours
  scale_shape_manual(values = c(1,1)) + # change shapes 
  labs(col = "Feed Mode") + 
  ggtitle("Weighted Unifrac for Feed Mode") +  # add title
  theme(
    plot.title = element_text(hjust = 0.5),  # centre title
    panel.background = element_rect(fill = "white"),  # Set background color to white
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank(),  # Remove minor grid lines
    axis.line = element_blank(), # remove axis lines 
    panel.border = element_rect(color = "black", fill = NA, size = 0.5), # add border 
    legend.key = element_rect(fill = "white")) + # Set legend background color to white 
  geom_hline(yintercept = 0, linetype = "dashed",color = "black", size = 0.25) + # add intercept at 0.0 
  geom_vline(xintercept = 0, linetype = "dashed", color = "black", size = 0.25) + # add intercept at 0.0 
  stat_ellipse(aes(fill = feed), level = 0.95, alpha = 0.3) + # Add ellipses 
  guides(shape = FALSE) # remove legend for shape 

print(pcoa_wu_feed_mode_pub_ready)

# Save plot
ggsave("PCoA Weighted Unifrac for Feed Mode Publication Ready.png", 
       plot = pcoa_wu_feed_mode_pub_ready, 
       height = 4, width = 5)

#### Permanova analysis (with birth mode controlled for) #### 

# Bray Curtis 
distance_braycurtis <- vegdist(t(otu_table(all_BMI_phyloseq_rare_new)), method="bray") 

all_BMI_data_bc <- data.frame(sample_data(all_BMI_phyloseq_rare_new)) 
adonis2(distance_braycurtis ~ mom_bmi_label*feed + baby_delivery, data=all_BMI_data_bc)

# Results: 

#                     Df SumOfSqs      R2      F Pr(>F)  
# mom_bmi_label       1   0.3142 0.03259 1.0075  0.375  
# feed                1   0.5287 0.05484 1.6954  0.095 .
# baby_delivery       1   0.1425 0.01478 0.4569  0.917  
# mom_bmi_label:feed  1   0.2353 0.02441 0.7547  0.612  
# Residual           27   8.4196 0.87338                
# Total              31   9.6403 1.00000                

# No signficant results :( 

# Weighted Unifrac: 

distance_unifrac <- UniFrac(all_BMI_phyloseq_rare_new, weighted=TRUE) 

all_BMI_data_wu <- data.frame(sample_data(all_BMI_phyloseq_rare_new))
adonis2(distance_unifrac ~ mom_bmi_label*feed + baby_delivery, data=all_BMI_data_wu)

# Results: 

#                    Df SumOfSqs      R2      F Pr(>F)  
# mom_bmi_label       1  0.05750 0.03054 0.9755  0.368  
# feed                1  0.15466 0.08216 2.6238  0.049 *
# baby_delivery       1  0.03358 0.01784 0.5697  0.683  
# mom_bmi_label:feed  1  0.04526 0.02404 0.7678  0.548  
# Residual           27  1.59146 0.84542                
# Total              31  1.88245 1.00000                

# Significant result for feed mode 
