#!/usr/bin/env Rscript
# MICB 475 project 2 initial beta diversity analysis 
# Emily 2023-10-30

library(vegan)
library(phyloseq)
library(dplyr)

#### Load in RData ####

load("all_BMI_phyloseq_rare_new.RData")

#### Permanova analysis ####  
# Bray Curtis
distance_braycurtis <- vegdist(t(otu_table(all_BMI_phyloseq_rare_new)), method="bray") 

all_BMI_data_bc <- data.frame(sample_data(all_BMI_phyloseq_rare_new)) 
adonis2(distance_braycurtis ~ mom_bmi_label*feed, data=all_BMI_data_bc)

# results: 
#                     Df SumOfSqs      R2      F Pr(>F)  
# mom_bmi_label       1   0.3142 0.03259 1.0263  0.358  
# feed                1   0.5287 0.05484 1.7271  0.086 .
# mom_bmi_label:feed  1   0.2261 0.02345 0.7386  0.636  
# Residual           28   8.5713 0.88911                
# Total              31   9.6403 1.00000  

# No significant results :(

# Permanova analysis for Weighted Unifrac 
distance_unifrac <- UniFrac(all_BMI_phyloseq_rare_new, weighted=TRUE) 

all_BMI_data_wu <- data.frame(sample_data(all_BMI_phyloseq_rare_new))
adonis2(distance_unifrac ~ mom_bmi_label*feed, data=all_BMI_data_wu)

# results: 
#                     Df SumOfSqs      R2      F Pr(>F)  
# mom_bmi_label       1  0.05750 0.03054 0.9909  0.378  
# feed                1  0.15466 0.08216 2.6654  0.047 *
# mom_bmi_label:feed  1  0.04563 0.02424 0.7864  0.516  
# Residual           28  1.62467 0.86306                
# Total              31  1.88245 1.00000   

# Significant result for feed 
